clean:
  rm -rf build
  cargo clean

build-static:
  mkdir -p build
  clang++ -std=c++17 -c -static -o build/libdb.o cpp/db.cpp
  ar r build/libdb.a build/libdb.o

build-shared:
  mkdir -p build
  clang++ -shared -fPIC cpp/db.cpp -o build/libdb.so

build: clean build-static build-shared

run:
  cargo r

fmt:
  clang-format --style Microsoft -i cpp/*.cpp cpp/*.hpp
  cargo fmt
